try:
    print(int("fail"))
except Exception as e:
    print(repr(e))
